import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import esbuildSvelte from "esbuild-svelte";
import { sveltePreprocess } from "svelte-preprocess";

const banner = `/* Garmin Connect probe — generated by esbuild. Source: src/ */\n`;
const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	plugins: [
		esbuildSvelte({
			// Component styles ride in the bundle; styles.css keeps only the
			// shared design tokens and anything Obsidian itself needs to see.
			compilerOptions: { css: "injected", dev: !prod },
			preprocess: sveltePreprocess(),
		}),
	],
	entryPoints: ["src/main.ts"],
	bundle: true,
	// `browser` makes esbuild refuse to shim node builtins instead of silently
	// bundling a polyfill that only works under Electron.
	platform: "browser",
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	mainFields: ["svelte", "browser", "module", "main"],
	// "production" makes esm-env resolve DEV to false, which lets esbuild drop
	// Svelte's dev-only branches instead of shipping them to a phone.
	conditions: prod ? ["svelte", "browser", "production"] : ["svelte", "browser", "development"],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
