import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import esbuildSvelte from "esbuild-svelte";
import { sveltePreprocess } from "svelte-preprocess";

const banner = `/* Garmin Connect probe — generated by esbuild. Source: src/ */\n`;
const prod = process.argv[2] === "production";

/**
 * Production drops the UI gallery.
 *
 * `__GALLERY__: false` already dead-codes the two call sites, but esbuild
 * still walks the import behind them: Svelte emits top-level `$.template(...)`
 * calls it cannot prove pure, so the gallery's markup rode along even with the
 * branch gone. Swapping the module for an empty one removes the whole graph —
 * bits-ui, the calendar, and every wrapper — instead of most of it.
 */
const dropGallery = {
	name: "drop-gallery",
	setup(build) {
		build.onResolve({ filter: /ui\/gallery-view$/ }, (args) => ({
			path: args.path,
			namespace: "dropped-gallery",
		}));
		build.onLoad({ filter: /.*/, namespace: "dropped-gallery" }, () => ({
			contents:
				"export const GARMIN_GALLERY_VIEW = '';\n" +
				"export class GarminGalleryView {}\n" +
				"export function openGallery() {}\n",
			loader: "js",
		}));
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	plugins: [
		...(prod ? [dropGallery] : []),
		esbuildSvelte({
			// Component styles ride in the bundle; styles.css keeps only the
			// shared design tokens and anything Obsidian itself needs to see.
			compilerOptions: { css: "injected", dev: !prod },
			preprocess: sveltePreprocess(),
			// bits-ui ships uncompiled .svelte, so its source is compiled here
			// too. Its warnings are not ours to fix and bury our own.
			filterWarnings: (w) => !w.filename?.includes("node_modules"),
		}),
	],
	entryPoints: ["src/main.ts"],
	bundle: true,
	// `browser` makes esbuild refuse to shim node builtins instead of silently
	// bundling a polyfill that only works under Electron.
	platform: "browser",
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	mainFields: ["svelte", "browser", "module", "main"],
	// "production" makes esm-env resolve DEV to false, which lets esbuild drop
	// Svelte's dev-only branches instead of shipping them to a phone.
	conditions: prod ? ["svelte", "browser", "production"] : ["svelte", "browser", "development"],
	// Dead-codes the UI gallery out of a production build. See build-flags.d.ts.
	define: { __GALLERY__: String(!prod) },
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
