import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/* Garmin Connect probe — generated by esbuild. Source: src/ */\n`;
const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	// `browser` makes esbuild refuse to shim node builtins instead of silently
	// bundling a polyfill that only works under Electron.
	platform: "browser",
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: false,
});

if (prod) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
